# Generated by Django 5.0.6 on 2024-06-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='description',
        ),
    ]
