# Generated by Django 5.0.6 on 2024-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_facility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.ImageField(blank=True, upload_to='facilities/'),
        ),
    ]
