# Generated by Django 5.0.6 on 2024-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_tag_blog_blogdescription_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
