# Generated by Django 5.0.6 on 2024-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blogdescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdescription',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdescription',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
