# Generated by Django 5.0.6 on 2024-06-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_amenity_icon_amenity_icon_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon_color',
        ),
    ]
