# Generated by Django 5.0.6 on 2024-06-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_getintouchsubject_getintouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_nbr',
        ),
    ]
