# Generated by Django 5.0.6 on 2024-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_booking_room_nbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
    ]
